title: 이슬이 포트폴리오
email: yapyap93@naver.com
description: 이슬이 어쩌구 저쩌구
baseurl: ''
url: 'https://yapyap93.github.io'
repository: yapyap93/yapyap93.github.io
exclude: 
  - node_modules
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock
author: master@mono.svn.io
image: ''
google_analytics:
  ua: ''
facebook:
  app_id: ''
  username:
twitter:
  username:
google_plus:
  username:
github_url:
  username:
sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules  