title: 'UM COMPANY'
project: 'UM COMPANY'
telephone: 010 8674 7526
telephone_link: 010-8674-7526
email: yap_on@naver.com
description: CREATIVE TEAM UM(음) 입니다
baseurl: ''
url: 'https://yapyap93.github.io'
repository: yapyap93/yapyap93.github.io
exclude: 
  - .gitignore
  - Gemfile
  - Gemfile.lock  
  - README.md  
image: 'assets/images/banner01.jpg'
avatar: '/assets/images/ssakssak.png'
slides:
  - assets/images/banner01.jpg
  - assets/images/banner02.jpg
facebook:
twitter:
instagram:  
about: |
  SNS와 Youtube 등 온라인 미디어 콘텐츠를 제작합니다.  
  기획부터 촬영, 편집까지의 제작 전반의 역량을 갖춰 정확한 커뮤니케이션과  
  빠르고 합리적인 콘텐츠를 만듭니다.
services: |
  This is a multi-line string. "special" metacharacters may  
service-item:
  - icon: fab fa-adobe
    text: Video Contents
  - icon: fas fa-film
    text: Viral Branded
  - icon: fas fa-gamepad
    text: SNS Contents
  - icon: fas fa-draw-polygon
    text: SNS Marketing
  - icon: fas fa-draw-polygon
    text: Live Commerce
portfolio: |
  This is a multi-line string.  
  "special" metacharacters may  
  appear here. The extent of this string is  
  indicated by indentation.   
portfolio-item:
  - image: https://i.ytimg.com/vi/9mG7sZ7ysvs/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBQ9iXdYKqSSOSFRUlWnPQIJ2NSQQ
    link: https://www.youtube.com/watch?v=9mG7sZ7ysvs
  - image: https://cdn.vox-cdn.com/thumbor/DRBDPQtWBm3Fslrag4dWWtmUmXk=/0x0:1280x720/1200x800/filters:focal(591x265:795x469)/cdn.vox-cdn.com/uploads/chorus_image/image/60208351/ali_a.0.jpg
    link: https://imagescdn.gettyimagesbank.com/500/19/662/369/0/1137628633.jpg
footer: |
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi     
sass:
  style: compressed
  load_paths:
    - _sass
