title: 'UM COMPANY'
project: 'UM COMPANY'
telephone: 010 8674 7526
email: yap_on@naver.com
description: CREATIVE TEAM UM(음) 입니다
baseurl: ''
url: 'https://yapyap93.github.io'
repository: yapyap93/yapyap93.github.io
exclude: 
  - .gitignore
  - Gemfile
  - Gemfile.lock  
  - README.md  
image: 'assets/images/banner01.jpg'
avatar: 'assets/images/banner01.jpg'
slides:
  - assets/images/banner01.jpg
  - assets/images/banner02.jpg
facebook:
twitter:
instagram:  
about: |
  SNS와 Youtube 등 온라인 미디어 콘텐츠를 제작합니다.  
  기획부터 촬영, 편집까지의 제작 전반의 역량을 갖춰 정확한 커뮤니케이션과  
  빠르고 합리적인 콘텐츠를 만듭니다.
service-item:
  - image: assets/images/about_video_contents.png
    text: Video Contents
  - image: assets/images/about_viral.png
    text: Viral ⋅ Branded
  - image: assets/images/about_sns_contents.png
    text: SNS Contents
  - image: assets/images/about_sns_marketing.png
    text: SNS Marketing
  - image: assets/images/about_live_commerce.png
    text: Live Commerce
portfolio: |
  This is a multi-line string.  
  "special" metacharacters may  
  appear here. The extent of this string is  
  indicated by indentation.   
portfolio-item:
  - image: https://img.youtube.com/vi/fz50p2FZo0c/hqdefault.jpg
    link: https://youtu.be/fz50p2FZo0c
    
  - image: 
    link: 
    
  - image:
    link:
    
  - image: 
    link: 
    
  - image: 
    link: 
    
  - image: 
    link: 
    
  - image: 
    link: 
    
sass:
  style: compressed
  load_paths:
    - _sass
