title: 이슬이 포트폴리오
project: yapyap93
telephone: 010xxxxxxxx
email: yapyap93@naver.com
description: 이슬이 어쩌구 저쩌구
baseurl: ''
url: 'https://yapyap93.github.io'
repository: yapyap93/yapyap93.github.io
exclude: 
  - .gitignore
  - Gemfile
  - Gemfile.lock  
  - README.md  
avatar: '/assets/images/ssakssak.png'
slides:
  - type: video/mp4
    file: assets/images/glitch01.mp4
  - type: video/mp4
    file: assets/images/glitch02.mp4
  - type: video/mp4
    file: assets/images/glitch03.mp4
facebook:
twitter:
instagram:  
about: |
  This is a multi-line string.  
  "special" metacharacters may  
  appear here. The extent of this string is  
  indicated by indentation.  
services: |
  This is a multi-line string. "special" metacharacters may  
service-item:
  - icon: fab fa-adobe
    text: design
  - icon: fas fa-film
    text: video    
  - icon: fas fa-gamepad
    text: game    
  - icon: fas fa-draw-polygon
    text: draw            
portfolio: |
  This is a multi-line string.  
  "special" metacharacters may  
  appear here. The extent of this string is  
  indicated by indentation.   
portfolio-item:
  - image: https://i.ytimg.com/vi/9mG7sZ7ysvs/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBQ9iXdYKqSSOSFRUlWnPQIJ2NSQQ
    link: https://www.youtube.com/watch?v=9mG7sZ7ysvs
  - image: https://cdn.vox-cdn.com/thumbor/DRBDPQtWBm3Fslrag4dWWtmUmXk=/0x0:1280x720/1200x800/filters:focal(591x265:795x469)/cdn.vox-cdn.com/uploads/chorus_image/image/60208351/ali_a.0.jpg
    link: https://imagescdn.gettyimagesbank.com/500/19/662/369/0/1137628633.jpg
footer: |
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi     
sass:
  style: compressed
  load_paths:
    - _sass